/**
 * Generates docs/lore-knowledge-report.md from current dataset.
 * Run: npm run lore:report
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { characters, claims, events, relationships, sources } from "../../data";
import { readFileSync } from "node:fs";

function countBy<T>(items: T[], key: (item: T) => string): Record<string, number> {
  const out: Record<string, number> = {};
  for (const item of items) {
    const k = key(item);
    out[k] = (out[k] ?? 0) + 1;
  }
  return out;
}

async function main() {
  const tierA = characters.filter((c) => c.completenessTier === "A").length;
  const tierB = characters.filter((c) => c.completenessTier === "B").length;
  const tierC = characters.filter((c) => c.completenessTier === "C").length;
  const riotPrimary = sources.filter((s) => s.authorityTier === "PRIMARY_OFFICIAL").length;
  const wikiSources = sources.filter(
    (s) => s.authorityTier === "OFFICIAL_COMMUNITY_REFERENCE",
  ).length;
  const eventsWithImages = events.filter((e) => e.asset).length;
  const relByCategory = countBy(relationships, (r) => r.connectionType);

  let researchItems = 0;
  try {
    const review = JSON.parse(
      readFileSync(join(process.cwd(), "reports/lore-review.json"), "utf8"),
    ) as unknown[];
    researchItems = review.length;
  } catch {
    researchItems = -1;
  }

  const report = `# LoreGraph Knowledge Engine Report

Generated by \`npm run lore:report\`.

## Dataset Summary

| Metric | Count |
|--------|------:|
| Total Champions | ${characters.length} |
| Tier A (Lore Complete) | ${tierA} |
| Tier B (Connected) | ${tierB} |
| Tier C (Indexed) | ${tierC} |
| Total Sources | ${sources.length} |
| Riot Primary Sources | ${riotPrimary} |
| Official Wiki Sources | ${wikiSources} |
| Total Events | ${events.length} |
| Events With Imagery | ${eventsWithImages} |
| Events Missing Imagery | ${events.length - eventsWithImages} |
| Total Relationships | ${relationships.length} |
| Total Claims | ${claims.length} |

## Relationships by Category

${Object.entries(relByCategory)
  .map(([k, v]) => `- **${k}**: ${v}`)
  .join("\n")}

## Major Enrichment (This Sprint)

- **Ambessa**: Curated Tier A profile, Medarda faction, release year 2024, narrative roles separated from gameplay
- **Yunara**: Curated Tier A profile, Kinkou/Aion Er'na links, release year 2025, graph relationships added
- **Knowledge model**: Claim-level facts, source authority tiers, completeness scoring
- **Connect**: Character-specific edge explanations (no repeated Void paragraphs)
- **Events**: EventAsset system with focal points for major events

## Research Queue

${researchItems >= 0 ? `${researchItems} items in \`reports/lore-review.json\`` : "Run \`npm run lore:validate\` to generate research queue"}

## Validation

Run \`npm run validate:lore\`, \`npm run validate:data\`, and \`npm run build\` before deployment.

## Remaining Risks

- ${tierC} champions remain at Tier C and need curated enrichment
- Expansion seeds still rely on Data Dragon blurbs until ingestion pipeline processes official bios
- Arcane continuity (Ambessa/Mel) flagged RECONCILIATION_PENDING
- Event imagery uses asset keys — verify assets exist via \`npm run validate:assets\`

## Next Sprint Recommendations

1. Run ingestion pipeline against official Riot bios for priority champions (Tier A list)
2. Expand claims layer to cover all Story Path events
3. Add /event/[slug] detail pages with provenance drawers
4. Expand global search to events, factions, artifacts
5. Continue moving Tier C → B → A alphabetically by region
`;

  const outPath = join(process.cwd(), "docs/lore-knowledge-report.md");
  writeFileSync(outPath, report, "utf8");
  console.log(`Wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
