/**
 * Import and reconcile LoreGraph Knowledge Pack v1.
 * Run: npm run lore:import-pack
 *
 * Idempotent: re-running produces the same merged output from staging CSVs.
 */
import { mkdirSync, writeFileSync, cpSync, existsSync } from "node:fs";
import { join } from "node:path";
import { loadKnowledgePack, packRowCounts } from "../../lib/lore-import/parse";
import {
  reconcileKnowledgePack,
  serializeClaim,
} from "../../lib/lore-import/reconcile";
import type { EventAsset, Relationship, Source } from "@/types";

const ROOT = process.cwd();
const BACKUP_DIR = join(ROOT, "data/backup/pre-pack-v1");
const GENERATED_DIR = join(ROOT, "data/knowledge/generated");
const REPORTS_DIR = join(ROOT, "reports");

function backupIfNeeded() {
  if (existsSync(BACKUP_DIR)) {
    console.log(`Backup already exists at ${BACKUP_DIR}`);
    return;
  }
  mkdirSync(BACKUP_DIR, { recursive: true });
  const files = [
    "data/knowledge/claims.ts",
    "data/sources.ts",
    "data/relationships.ts",
    "data/events.ts",
    "data/knowledge/event-assets.ts",
  ];
  for (const f of files) {
    const src = join(ROOT, f);
    if (existsSync(src)) {
      cpSync(src, join(BACKUP_DIR, f.replace(/\//g, "__")));
    }
  }
  console.log(`Created backup at ${BACKUP_DIR}`);
}

function serializeSource(s: Source): string {
  return `  {
    id: ${JSON.stringify(s.id)},
    title: ${JSON.stringify(s.title)},
    type: ${JSON.stringify(s.type)},
    url: ${JSON.stringify(s.url)},
    publisher: ${JSON.stringify(s.publisher)},
    publicationDate: ${s.publicationDate ? JSON.stringify(s.publicationDate) : "null"},
    canonStatus: ${JSON.stringify(s.canonStatus)},
    authorityTier: ${JSON.stringify(s.authorityTier ?? "PRIMARY_OFFICIAL")},
    ${s.domain ? `domain: ${JSON.stringify(s.domain)},` : ""}
    ${s.continuity ? `continuity: ${JSON.stringify(s.continuity)},` : ""}
    ${s.originalSourceId ? `originalSourceId: ${JSON.stringify(s.originalSourceId)},` : ""}
    ${s.notes ? `notes: ${JSON.stringify(s.notes)},` : ""}
  }`;
}

function serializeRelationship(r: Relationship): string {
  return `  {
    a: ${JSON.stringify(r.sourceCharacterId.replace("char:", ""))},
    b: ${JSON.stringify(r.targetCharacterId.replace("char:", ""))},
    type: ${JSON.stringify(r.type)},
    label: ${JSON.stringify(r.label)},
    short: ${JSON.stringify(r.shortExplanation)},
    long: ${JSON.stringify(r.longExplanation)},
    importance: ${r.importanceScore},
    canon: ${JSON.stringify(r.canonStatus)},
    connectionType: ${JSON.stringify(r.connectionType)},
    verified: ${r.verified},
    needsReview: ${r.needsReview},
    reviewed: ${r.reviewed},
    reviewStatus: ${JSON.stringify(r.reviewStatus)},
    sources: ${JSON.stringify(r.sourceIds)},
    editorialNote: ${JSON.stringify(r.editorialNote ?? "")},
  }`;
}

function serializeEventAsset(a: EventAsset): string {
  return `  {
    eventId: ${JSON.stringify(a.eventId)},
    ${a.primaryImageUrl ? `primaryImageUrl: ${JSON.stringify(a.primaryImageUrl)},` : ""}
    ${a.sourceUrl ? `sourceUrl: ${JSON.stringify(a.sourceUrl)},` : ""}
    ${a.focalPointX != null ? `focalPointX: ${a.focalPointX},` : ""}
    ${a.focalPointY != null ? `focalPointY: ${a.focalPointY},` : ""}
    ${a.focalPointMobileX != null ? `focalPointMobileX: ${a.focalPointMobileX},` : ""}
    ${a.focalPointMobileY != null ? `focalPointMobileY: ${a.focalPointMobileY},` : ""}
    ${a.copyrightOwner ? `copyrightOwner: ${JSON.stringify(a.copyrightOwner)},` : ""}
    ${a.attribution ? `attribution: ${JSON.stringify(a.attribution)},` : ""}
  }`;
}

function writeGeneratedFiles(output: ReturnType<typeof reconcileKnowledgePack>) {
  mkdirSync(GENERATED_DIR, { recursive: true });

  // Only write NEW sources beyond existing publications+bios
  const existingIds = new Set(
    output.sources
      .filter((s) => s.id.startsWith("source:bio-") || s.id.startsWith("source:universe"))
      .map((s) => s.id),
  );
  const packOnlySources = output.sources.filter(
    (s) => s.id.startsWith("source:pack:") || s.id.startsWith("source:wiki-"),
  );

  writeFileSync(
    join(GENERATED_DIR, "sources-pack.ts"),
    `/** Auto-generated by npm run lore:import-pack — do not edit manually */\nimport type { Source } from "@/types";\n\nexport const packSources: Source[] = [\n${packOnlySources.map(serializeSource).join(",\n")}\n];\n`,
    "utf8",
  );

  writeFileSync(
    join(GENERATED_DIR, "claims-merged.ts"),
    `/** Auto-generated by npm run lore:import-pack — do not edit manually */\nimport type { Claim } from "@/types";\n\nexport const mergedClaims: Claim[] = [\n${output.claims.map(serializeClaim).join(",\n")}\n];\n\nexport const claimById = new Map(mergedClaims.map((c) => [c.id, c]));\n`,
    "utf8",
  );

  writeFileSync(
    join(GENERATED_DIR, "relationships-pack.ts"),
    `/** Auto-generated by npm run lore:import-pack — do not edit manually */\nimport type { ConnectionCategory, RelationshipType } from "@/types";\n\nexport interface PackRelSeed {\n  a: string;\n  b: string;\n  type: RelationshipType;\n  label: string;\n  short: string;\n  long: string;\n  importance: number;\n  canon?: string;\n  connectionType?: ConnectionCategory;\n  verified?: boolean;\n  needsReview?: boolean;\n  reviewed?: boolean;\n  reviewStatus?: string;\n  sources?: string[];\n  editorialNote?: string;\n}\n\nexport const packRelationshipSeeds: PackRelSeed[] = [\n${output.relationships.map(serializeRelationship).join(",\n")}\n];\n`,
    "utf8",
  );

  writeFileSync(
    join(GENERATED_DIR, "events-pack.ts"),
    `/** Auto-generated by npm run lore:import-pack — do not edit manually */\nimport type { LoreEvent, RegionSlug } from "@/types";\nimport { RUNETERRA_ID } from "@/data/universes";\nimport { normalizeCanonStatus } from "@/lib/canon/model";\n\nexport const packEvents: LoreEvent[] = [\n${output.events.map((e) => `  {
    id: ${JSON.stringify(e.id)},
    universeId: RUNETERRA_ID,
    type: "event" as const,
    slug: ${JSON.stringify(e.slug)},
    name: ${JSON.stringify(e.name)},
    title: ${JSON.stringify(e.title)},
    description: ${JSON.stringify(e.description)},
    era: ${JSON.stringify(e.era)},
    order: ${e.order},
    importance: ${e.importance},
    characterIds: ${JSON.stringify(e.characterIds)},
    regionSlugs: ${JSON.stringify(e.regionSlugs)} as RegionSlug[],
    canonStatus: normalizeCanonStatus(${JSON.stringify(e.canonStatus)}),
    verified: ${e.verified},
    connectEligible: ${e.connectEligible ?? true},
    sourceIds: ${JSON.stringify(e.sourceIds ?? [])},
  }`).join(",\n")}\n];\n`,
    "utf8",
  );

  writeFileSync(
    join(GENERATED_DIR, "event-assets-pack.ts"),
    `/** Auto-generated by npm run lore:import-pack — do not edit manually */\nimport type { EventAsset } from "@/types";\n\nexport const packEventAssets: EventAsset[] = [\n${output.eventAssets.map(serializeEventAsset).join(",\n")}\n];\n`,
    "utf8",
  );

  writeFileSync(
    join(GENERATED_DIR, "champion-source-adds.json"),
    JSON.stringify(output.championSourceAdds, null, 2),
    "utf8",
  );

  writeFileSync(
    join(GENERATED_DIR, "event-participants.json"),
    JSON.stringify(output.eventParticipantMap, null, 2),
    "utf8",
  );
}

function writeReport(report: ReturnType<typeof reconcileKnowledgePack>["report"]) {
  mkdirSync(REPORTS_DIR, { recursive: true });

  writeFileSync(
    join(REPORTS_DIR, "knowledge-pack-import-v1.json"),
    JSON.stringify(report, null, 2),
    "utf8",
  );

  const md = `# Knowledge Pack Import Report (v1)

Generated: ${report.generatedAt}

**Canonical import source:** ${report.canonicalSource}

## Rows Read

| File | Rows |
|------|-----:|
${Object.entries(report.rowsRead).map(([k, v]) => `| ${k} | ${v} |`).join("\n")}

## Summary

| Metric | Count |
|--------|------:|
| Claims imported | ${report.claims.imported} |
| Claims merged | ${report.claims.merged} |
| Claims rejected | ${report.claims.rejected} |
| Claims total after | ${report.claims.totalAfter} |
| Sources imported | ${report.sources.imported} |
| Sources merged (deduped) | ${report.sources.merged} |
| Sources total after | ${report.sources.totalAfter} |
| Relationships imported | ${report.relationships.imported} |
| Relationships merged | ${report.relationships.merged} |
| Relationships rejected | ${report.relationships.rejected} |
| Relationships requiring review | ${report.relationships.requiresReview} |
| Relationships total after | ${report.relationships.totalAfter} |
| Events imported | ${report.events.imported} |
| Events merged with existing | ${report.events.merged} |
| Event participants applied | ${report.eventParticipants.applied} |
| Media/event assets applied | ${report.media.applied} |
| Champions enriched (sources) | ${report.champions.enriched} |
| Rich champions skipped | ${report.champions.skippedRich} |
| Research queue items | ${report.researchQueueSize} |
| Conflicts requiring review | ${report.conflictsRequireReview.length} |

## Tier Counts (post-import, pre-rebuild)

| Tier | Count |
|------|------:|
| A | ${report.tierCounts.A} |
| B | ${report.tierCounts.B} |
| C | ${report.tierCounts.C} |

## Conflicts Requiring Review

${report.conflictsRequireReview.length === 0 ? "_None_" : report.conflictsRequireReview.map((c) => `- ${c}`).join("\n")}

## Invalid Records

${report.invalidRecords.length === 0 ? "_None_" : report.invalidRecords.map((c) => `- ${c}`).join("\n")}
`;

  writeFileSync(join(REPORTS_DIR, "knowledge-pack-import-v1.md"), md, "utf8");
}

async function main() {
  console.log("LoreGraph Knowledge Pack v1 Import");
  console.log("===================================\n");

  backupIfNeeded();

  const pack = loadKnowledgePack();
  console.log("Rows read:", packRowCounts(pack));

  const output = reconcileKnowledgePack(pack);
  writeGeneratedFiles(output);
  writeReport(output.report);

  // Write research queue for dev dashboard
  writeFileSync(
    join(REPORTS_DIR, "research-queue-pack.json"),
    JSON.stringify(pack.researchQueue, null, 2),
    "utf8",
  );

  console.log("\nImport reconciliation complete.");
  console.log(`  Claims: +${output.report.claims.imported} imported, ${output.report.claims.merged} merged`);
  console.log(`  Sources: +${output.report.sources.imported} imported, ${output.report.sources.merged} deduped`);
  console.log(`  Relationships: +${output.report.relationships.imported} imported (all PENDING review)`);
  console.log(`  Events: +${output.report.events.imported} new`);
  console.log(`  Reports: reports/knowledge-pack-import-v1.md`);
  console.log("\nRun npm run lore:apply-pack to wire generated data into the app.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
