/**
 * Generates font-derived name constellation anchor data from Instrument Serif.
 * Run: npx tsx scripts/cinematic/generate-name-glyphs.ts
 */
import fs from "node:fs";
import path from "node:path";
import opentype from "opentype.js";
import type { Font } from "opentype.js";
import {
  buildConstellationFromGlyphs,
  flattenGlyphPath,
  layoutGlyphs,
} from "../../lib/cinematic-v3/glyph-constellation";

const FONT_PATH = path.join(process.cwd(), "public/fonts/InstrumentSerif-Regular.ttf");
const OUT_PATH = path.join(process.cwd(), "data/cinematic/name-glyphs.generated.ts");

const SPECS = [
  { id: "name:aatrox", characterId: "char:aatrox", displayName: "AATROX", heroStarId: "name-hero", targetWidth: 0.7 },
  { id: "name:yasuo", characterId: "char:yasuo", displayName: "YASUO", heroStarId: "name-hero", targetWidth: 0.7 },
  { id: "name:yone", characterId: "char:yone", displayName: "YONE", heroStarId: "name-hero", targetWidth: 0.68 },
  { id: "name:viego", characterId: "char:viego", displayName: "VIEGO", heroStarId: "name-hero", targetWidth: 0.7 },
  { id: "name:skarner", characterId: "char:skarner", displayName: "SKARNER", heroStarId: "name-hero", targetWidth: 0.76 },
];

const FONT_SIZE = 120;
const TRACKING = 0.12;

function main() {
  const font = opentype.parse(fs.readFileSync(FONT_PATH)) as Font;
  const generated: Record<string, ReturnType<typeof buildConstellationFromGlyphs>> = {};

  for (const spec of SPECS) {
    const chars = spec.displayName.split("");
    const layout = layoutGlyphs(
      chars,
      (char) => {
        const glyph = font.charToGlyph(char);
        if (!glyph) return null;
        const path = glyph.getPath(0, 0, FONT_SIZE);
        const contours = flattenGlyphPath(path.commands as never[], 5.5);
        return {
          contours,
          advance: (glyph.advanceWidth ?? font.getAdvanceWidth(char, FONT_SIZE)) / FONT_SIZE,
        };
      },
      TRACKING,
    );
    if (!layout) throw new Error(`Failed to layout ${spec.displayName}`);
    generated[spec.id] = buildConstellationFromGlyphs({
      ...spec,
      layout,
      targetWidth: spec.targetWidth,
      centerY: 0.44,
    });
    console.log(
      `${spec.displayName}: ${generated[spec.id].anchors.length} anchors, ${generated[spec.id].lines.length} lines`,
    );
  }

  const body = `/** Auto-generated by scripts/cinematic/generate-name-glyphs.ts — do not edit. */
import type { ChampionConstellationAnchor, ConstellationContourGroup, ConstellationLine } from "@/types";

export interface GeneratedGlyphConstellation {
  anchors: ChampionConstellationAnchor[];
  lines: ConstellationLine[];
  contourGroups: ConstellationContourGroup[];
}

export const GENERATED_NAME_GLYPHS: Record<string, GeneratedGlyphConstellation> = ${JSON.stringify(generated, null, 2)};
`;

  fs.writeFileSync(OUT_PATH, body);
  console.log(`Wrote ${OUT_PATH}`);
}

main();
